<?php

/**
 * BaseProject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_id
 * @property string $title
 * @property date $response_wanted
 * @property string $description
 * 
 * @method integer getProjectId()       Returns the current record's "project_id" value
 * @method string  getTitle()           Returns the current record's "title" value
 * @method date    getResponseWanted()  Returns the current record's "response_wanted" value
 * @method string  getDescription()     Returns the current record's "description" value
 * @method Project setProjectId()       Sets the current record's "project_id" value
 * @method Project setTitle()           Sets the current record's "title" value
 * @method Project setResponseWanted()  Sets the current record's "response_wanted" value
 * @method Project setDescription()     Sets the current record's "description" value
 * 
 * @package    dfmarketplace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseProject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project');
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('response_wanted', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}