<?php

/**
 * BaseProject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $project_type_id
 * @property string $description
 * @property integer $stage_id
 * @property string $wiki_page
 * @property integer $contact_id
 * @property Doctrine_Collection $WorkshopProject
 * @property Doctrine_Collection $ProjectPerson
 * @property Doctrine_Collection $RequestedSkills
 * @property Doctrine_Collection $GoodProject
 * @property Doctrine_Collection $ValueProject
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method integer             getProjectTypeId()   Returns the current record's "project_type_id" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method integer             getStageId()         Returns the current record's "stage_id" value
 * @method string              getWikiPage()        Returns the current record's "wiki_page" value
 * @method integer             getContactId()       Returns the current record's "contact_id" value
 * @method Doctrine_Collection getWorkshopProject() Returns the current record's "WorkshopProject" collection
 * @method Doctrine_Collection getProjectPerson()   Returns the current record's "ProjectPerson" collection
 * @method Doctrine_Collection getRequestedSkills() Returns the current record's "RequestedSkills" collection
 * @method Doctrine_Collection getGoodProject()     Returns the current record's "GoodProject" collection
 * @method Doctrine_Collection getValueProject()    Returns the current record's "ValueProject" collection
 * @method Project             setId()              Sets the current record's "id" value
 * @method Project             setProjectTypeId()   Sets the current record's "project_type_id" value
 * @method Project             setDescription()     Sets the current record's "description" value
 * @method Project             setStageId()         Sets the current record's "stage_id" value
 * @method Project             setWikiPage()        Sets the current record's "wiki_page" value
 * @method Project             setContactId()       Sets the current record's "contact_id" value
 * @method Project             setWorkshopProject() Sets the current record's "WorkshopProject" collection
 * @method Project             setProjectPerson()   Sets the current record's "ProjectPerson" collection
 * @method Project             setRequestedSkills() Sets the current record's "RequestedSkills" collection
 * @method Project             setGoodProject()     Sets the current record's "GoodProject" collection
 * @method Project             setValueProject()    Sets the current record's "ValueProject" collection
 * 
 * @package    dfmarketplace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseProject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('project_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 4095, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '4095',
             ));
        $this->hasColumn('stage_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('wiki_page', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('contact_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->setAttribute(Doctrine_Core::ATTR_EXPORT, Doctrine_Core::EXPORT_ALL);
        $this->setAttribute(Doctrine_Core::ATTR_VALIDATE, true);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('WorkshopProject', array(
             'local' => 'id',
             'foreign' => 'project_id'));

        $this->hasMany('ProjectPerson', array(
             'local' => 'id',
             'foreign' => 'project_id'));

        $this->hasMany('SkillProject as RequestedSkills', array(
             'local' => 'id',
             'foreign' => 'project_id'));

        $this->hasMany('GoodProject', array(
             'local' => 'id',
             'foreign' => 'project_id'));

        $this->hasMany('ValueProject', array(
             'local' => 'id',
             'foreign' => 'project_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}