<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Skill', 'doctrine');

/**
 * BaseSkill
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $SkillPerson
 * @property Doctrine_Collection $SkillProject
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method timestamp           getCreatedAt()    Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()    Returns the current record's "updated_at" value
 * @method Doctrine_Collection getSkillPerson()  Returns the current record's "SkillPerson" collection
 * @method Doctrine_Collection getSkillProject() Returns the current record's "SkillProject" collection
 * @method Skill               setId()           Sets the current record's "id" value
 * @method Skill               setName()         Sets the current record's "name" value
 * @method Skill               setCreatedAt()    Sets the current record's "created_at" value
 * @method Skill               setUpdatedAt()    Sets the current record's "updated_at" value
 * @method Skill               setSkillPerson()  Sets the current record's "SkillPerson" collection
 * @method Skill               setSkillProject() Sets the current record's "SkillProject" collection
 * 
 * @package    dfmarketplace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseSkill extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('skill');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SkillPerson', array(
             'local' => 'id',
             'foreign' => 'skill_id'));

        $this->hasMany('SkillProject', array(
             'local' => 'id',
             'foreign' => 'skill_id'));
    }
}