<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ValueWorkstory', 'doctrine');

/**
 * BaseValueWorkstory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $workstory_id
 * @property integer $value_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Value $Value
 * @property Workstory $Workstory
 * 
 * @method integer        getWorkstoryId()  Returns the current record's "workstory_id" value
 * @method integer        getValueId()      Returns the current record's "value_id" value
 * @method timestamp      getCreatedAt()    Returns the current record's "created_at" value
 * @method timestamp      getUpdatedAt()    Returns the current record's "updated_at" value
 * @method Value          getValue()        Returns the current record's "Value" value
 * @method Workstory      getWorkstory()    Returns the current record's "Workstory" value
 * @method ValueWorkstory setWorkstoryId()  Sets the current record's "workstory_id" value
 * @method ValueWorkstory setValueId()      Sets the current record's "value_id" value
 * @method ValueWorkstory setCreatedAt()    Sets the current record's "created_at" value
 * @method ValueWorkstory setUpdatedAt()    Sets the current record's "updated_at" value
 * @method ValueWorkstory setValue()        Sets the current record's "Value" value
 * @method ValueWorkstory setWorkstory()    Sets the current record's "Workstory" value
 * 
 * @package    dfmarketplace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseValueWorkstory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('value_workstory');
        $this->hasColumn('workstory_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('value_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Value', array(
             'local' => 'value_id',
             'foreign' => 'id'));

        $this->hasOne('Workstory', array(
             'local' => 'workstory_id',
             'foreign' => 'id'));
    }
}