<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DreamfishGroup', 'doctrine');

/**
 * BaseDreamfishGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $dreamfish_group_type_id
 * @property string $location
 * @property string $interest
 * @property integer $contact_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Person $Person
 * @property DreamfishGroupType $DreamfishGroupType
 * 
 * @method integer            getId()                      Returns the current record's "id" value
 * @method integer            getDreamfishGroupTypeId()    Returns the current record's "dreamfish_group_type_id" value
 * @method string             getLocation()                Returns the current record's "location" value
 * @method string             getInterest()                Returns the current record's "interest" value
 * @method integer            getContactId()               Returns the current record's "contact_id" value
 * @method timestamp          getCreatedAt()               Returns the current record's "created_at" value
 * @method timestamp          getUpdatedAt()               Returns the current record's "updated_at" value
 * @method Person             getPerson()                  Returns the current record's "Person" value
 * @method DreamfishGroupType getDreamfishGroupType()      Returns the current record's "DreamfishGroupType" value
 * @method DreamfishGroup     setId()                      Sets the current record's "id" value
 * @method DreamfishGroup     setDreamfishGroupTypeId()    Sets the current record's "dreamfish_group_type_id" value
 * @method DreamfishGroup     setLocation()                Sets the current record's "location" value
 * @method DreamfishGroup     setInterest()                Sets the current record's "interest" value
 * @method DreamfishGroup     setContactId()               Sets the current record's "contact_id" value
 * @method DreamfishGroup     setCreatedAt()               Sets the current record's "created_at" value
 * @method DreamfishGroup     setUpdatedAt()               Sets the current record's "updated_at" value
 * @method DreamfishGroup     setPerson()                  Sets the current record's "Person" value
 * @method DreamfishGroup     setDreamfishGroupType()      Sets the current record's "DreamfishGroupType" value
 * 
 * @package    dfmarketplace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDreamfishGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dreamfish_group');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('dreamfish_group_type_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('location', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('interest', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('contact_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Person', array(
             'local' => 'contact_id',
             'foreign' => 'id'));

        $this->hasOne('DreamfishGroupType', array(
             'local' => 'dreamfish_group_type_id',
             'foreign' => 'id'));
    }
}