<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WorkshopProject', 'doctrine');

/**
 * BaseWorkshopProject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $workshop_id
 * @property integer $project_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Project $Project
 * @property Workshop $Workshop
 * 
 * @method integer         getWorkshopId()  Returns the current record's "workshop_id" value
 * @method integer         getProjectId()   Returns the current record's "project_id" value
 * @method timestamp       getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp       getUpdatedAt()   Returns the current record's "updated_at" value
 * @method Project         getProject()     Returns the current record's "Project" value
 * @method Workshop        getWorkshop()    Returns the current record's "Workshop" value
 * @method WorkshopProject setWorkshopId()  Sets the current record's "workshop_id" value
 * @method WorkshopProject setProjectId()   Sets the current record's "project_id" value
 * @method WorkshopProject setCreatedAt()   Sets the current record's "created_at" value
 * @method WorkshopProject setUpdatedAt()   Sets the current record's "updated_at" value
 * @method WorkshopProject setProject()     Sets the current record's "Project" value
 * @method WorkshopProject setWorkshop()    Sets the current record's "Workshop" value
 * 
 * @package    dfmarketplace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseWorkshopProject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('workshop_project');
        $this->hasColumn('workshop_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('project_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id'));

        $this->hasOne('Workshop', array(
             'local' => 'workshop_id',
             'foreign' => 'id'));
    }
}