<?php

/**
 * BaseProjectRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $project_id
 * @property string $request
 * @property date $deadline
 * @property Project $Project
 * 
 * @method integer        getId()         Returns the current record's "id" value
 * @method integer        getProjectId()  Returns the current record's "project_id" value
 * @method string         getRequest()    Returns the current record's "request" value
 * @method date           getDeadline()   Returns the current record's "deadline" value
 * @method Project        getProject()    Returns the current record's "Project" value
 * @method ProjectRequest setId()         Sets the current record's "id" value
 * @method ProjectRequest setProjectId()  Sets the current record's "project_id" value
 * @method ProjectRequest setRequest()    Sets the current record's "request" value
 * @method ProjectRequest setDeadline()   Sets the current record's "deadline" value
 * @method ProjectRequest setProject()    Sets the current record's "Project" value
 * 
 * @package    dfmarketplace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseProjectRequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_request');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('request', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('deadline', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id'));
    }
}