<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WorkshopPerson', 'doctrine');

/**
 * BaseWorkshopPerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $workshop_id
 * @property integer $person_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Person $Person
 * @property Workshop $Workshop
 * 
 * @method integer        getWorkshopId()  Returns the current record's "workshop_id" value
 * @method integer        getPersonId()    Returns the current record's "person_id" value
 * @method timestamp      getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp      getUpdatedAt()   Returns the current record's "updated_at" value
 * @method Person         getPerson()      Returns the current record's "Person" value
 * @method Workshop       getWorkshop()    Returns the current record's "Workshop" value
 * @method WorkshopPerson setWorkshopId()  Sets the current record's "workshop_id" value
 * @method WorkshopPerson setPersonId()    Sets the current record's "person_id" value
 * @method WorkshopPerson setCreatedAt()   Sets the current record's "created_at" value
 * @method WorkshopPerson setUpdatedAt()   Sets the current record's "updated_at" value
 * @method WorkshopPerson setPerson()      Sets the current record's "Person" value
 * @method WorkshopPerson setWorkshop()    Sets the current record's "Workshop" value
 * 
 * @package    dfmarketplace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseWorkshopPerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('workshop_person');
        $this->hasColumn('workshop_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('person_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id'));

        $this->hasOne('Workshop', array(
             'local' => 'workshop_id',
             'foreign' => 'id'));
    }
}