<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PaymentMethodAttributes', 'doctrine');

/**
 * BasePaymentMethodAttributes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $attribute_list
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $PaymentMethod
 * 
 * @method integer                 getId()             Returns the current record's "id" value
 * @method string                  getAttributeList()  Returns the current record's "attribute_list" value
 * @method timestamp               getCreatedAt()      Returns the current record's "created_at" value
 * @method timestamp               getUpdatedAt()      Returns the current record's "updated_at" value
 * @method Doctrine_Collection     getPaymentMethod()  Returns the current record's "PaymentMethod" collection
 * @method PaymentMethodAttributes setId()             Sets the current record's "id" value
 * @method PaymentMethodAttributes setAttributeList()  Sets the current record's "attribute_list" value
 * @method PaymentMethodAttributes setCreatedAt()      Sets the current record's "created_at" value
 * @method PaymentMethodAttributes setUpdatedAt()      Sets the current record's "updated_at" value
 * @method PaymentMethodAttributes setPaymentMethod()  Sets the current record's "PaymentMethod" collection
 * 
 * @package    dfmarketplace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePaymentMethodAttributes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('payment_method_attributes');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('attribute_list', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PaymentMethod', array(
             'local' => 'id',
             'foreign' => 'payment_method_attributes_id'));
    }
}