<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LanguagePerson', 'doctrine');

/**
 * BaseLanguagePerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $person_id
 * @property integer $language_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Language $Language
 * @property Person $Person
 * 
 * @method integer        getPersonId()    Returns the current record's "person_id" value
 * @method integer        getLanguageId()  Returns the current record's "language_id" value
 * @method timestamp      getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp      getUpdatedAt()   Returns the current record's "updated_at" value
 * @method Language       getLanguage()    Returns the current record's "Language" value
 * @method Person         getPerson()      Returns the current record's "Person" value
 * @method LanguagePerson setPersonId()    Sets the current record's "person_id" value
 * @method LanguagePerson setLanguageId()  Sets the current record's "language_id" value
 * @method LanguagePerson setCreatedAt()   Sets the current record's "created_at" value
 * @method LanguagePerson setUpdatedAt()   Sets the current record's "updated_at" value
 * @method LanguagePerson setLanguage()    Sets the current record's "Language" value
 * @method LanguagePerson setPerson()      Sets the current record's "Person" value
 * 
 * @package    dfmarketplace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseLanguagePerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('language_person');
        $this->hasColumn('person_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('language_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Language', array(
             'local' => 'language_id',
             'foreign' => 'id'));

        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id'));
    }
}