<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Workstory', 'doctrine');

/**
 * BaseWorkstory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property timestamp $date
 * @property integer $person_id
 * @property string $video_embed
 * @property string $text
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $ValueWorkstory
 * @property Doctrine_Collection $WorkstoryWorkshop
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getTitle()             Returns the current record's "title" value
 * @method timestamp           getDate()              Returns the current record's "date" value
 * @method integer             getPersonId()          Returns the current record's "person_id" value
 * @method string              getVideoEmbed()        Returns the current record's "video_embed" value
 * @method string              getText()              Returns the current record's "text" value
 * @method timestamp           getCreatedAt()         Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()         Returns the current record's "updated_at" value
 * @method Doctrine_Collection getValueWorkstory()    Returns the current record's "ValueWorkstory" collection
 * @method Doctrine_Collection getWorkstoryWorkshop() Returns the current record's "WorkstoryWorkshop" collection
 * @method Workstory           setId()                Sets the current record's "id" value
 * @method Workstory           setTitle()             Sets the current record's "title" value
 * @method Workstory           setDate()              Sets the current record's "date" value
 * @method Workstory           setPersonId()          Sets the current record's "person_id" value
 * @method Workstory           setVideoEmbed()        Sets the current record's "video_embed" value
 * @method Workstory           setText()              Sets the current record's "text" value
 * @method Workstory           setCreatedAt()         Sets the current record's "created_at" value
 * @method Workstory           setUpdatedAt()         Sets the current record's "updated_at" value
 * @method Workstory           setValueWorkstory()    Sets the current record's "ValueWorkstory" collection
 * @method Workstory           setWorkstoryWorkshop() Sets the current record's "WorkstoryWorkshop" collection
 * 
 * @package    dfmarketplace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseWorkstory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('workstory');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('person_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('video_embed', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ValueWorkstory', array(
             'local' => 'id',
             'foreign' => 'workstory_id'));

        $this->hasMany('WorkstoryWorkshop', array(
             'local' => 'id',
             'foreign' => 'workstory_id'));
    }
}