<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ValuePerson', 'doctrine');

/**
 * BaseValuePerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $person_id
 * @property integer $value_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Person $Person
 * @property Value $Value
 * 
 * @method integer     getPersonId()   Returns the current record's "person_id" value
 * @method integer     getValueId()    Returns the current record's "value_id" value
 * @method timestamp   getCreatedAt()  Returns the current record's "created_at" value
 * @method timestamp   getUpdatedAt()  Returns the current record's "updated_at" value
 * @method Person      getPerson()     Returns the current record's "Person" value
 * @method Value       getValue()      Returns the current record's "Value" value
 * @method ValuePerson setPersonId()   Sets the current record's "person_id" value
 * @method ValuePerson setValueId()    Sets the current record's "value_id" value
 * @method ValuePerson setCreatedAt()  Sets the current record's "created_at" value
 * @method ValuePerson setUpdatedAt()  Sets the current record's "updated_at" value
 * @method ValuePerson setPerson()     Sets the current record's "Person" value
 * @method ValuePerson setValue()      Sets the current record's "Value" value
 * 
 * @package    dfmarketplace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseValuePerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('value_person');
        $this->hasColumn('person_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('value_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id'));

        $this->hasOne('Value', array(
             'local' => 'value_id',
             'foreign' => 'id'));
    }
}