<?php

/**
 * BaseProjectSkill
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_id
 * @property integer $skill_id
 * @property Project $Project
 * @property Skill $Skill
 * 
 * @method integer      getProjectId()  Returns the current record's "project_id" value
 * @method integer      getSkillId()    Returns the current record's "skill_id" value
 * @method Project      getProject()    Returns the current record's "Project" value
 * @method Skill        getSkill()      Returns the current record's "Skill" value
 * @method ProjectSkill setProjectId()  Sets the current record's "project_id" value
 * @method ProjectSkill setSkillId()    Sets the current record's "skill_id" value
 * @method ProjectSkill setProject()    Sets the current record's "Project" value
 * @method ProjectSkill setSkill()      Sets the current record's "Skill" value
 * 
 * @package    dfmarketplace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseProjectSkill extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_skill');
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('skill_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id'));

        $this->hasOne('Skill', array(
             'local' => 'skill_id',
             'foreign' => 'id'));
    }
}