<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GoodProject', 'doctrine');

/**
 * BaseGoodProject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $good_id
 * @property integer $project_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Good $Good
 * @property Project $Project
 * 
 * @method integer     getGoodId()     Returns the current record's "good_id" value
 * @method integer     getProjectId()  Returns the current record's "project_id" value
 * @method timestamp   getCreatedAt()  Returns the current record's "created_at" value
 * @method timestamp   getUpdatedAt()  Returns the current record's "updated_at" value
 * @method Good        getGood()       Returns the current record's "Good" value
 * @method Project     getProject()    Returns the current record's "Project" value
 * @method GoodProject setGoodId()     Sets the current record's "good_id" value
 * @method GoodProject setProjectId()  Sets the current record's "project_id" value
 * @method GoodProject setCreatedAt()  Sets the current record's "created_at" value
 * @method GoodProject setUpdatedAt()  Sets the current record's "updated_at" value
 * @method GoodProject setGood()       Sets the current record's "Good" value
 * @method GoodProject setProject()    Sets the current record's "Project" value
 * 
 * @package    dfmarketplace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseGoodProject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('good_project');
        $this->hasColumn('good_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('project_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Good', array(
             'local' => 'good_id',
             'foreign' => 'id'));

        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id'));
    }
}