<?php

/**
 * BaseProjectValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_id
 * @property integer $value_id
 * @property Project $Project
 * 
 * @method integer      getProjectId()  Returns the current record's "project_id" value
 * @method integer      getValueId()    Returns the current record's "value_id" value
 * @method Project      getProject()    Returns the current record's "Project" value
 * @method ProjectValue setProjectId()  Sets the current record's "project_id" value
 * @method ProjectValue setValueId()    Sets the current record's "value_id" value
 * @method ProjectValue setProject()    Sets the current record's "Project" value
 * 
 * @package    dfmarketplace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseProjectValue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_value');
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('value_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id'));
    }
}