<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WorkstoryPerson', 'doctrine');

/**
 * BaseWorkstoryPerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $workstory_id
 * @property integer $person_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Person $Person
 * 
 * @method integer         getWorkstoryId()  Returns the current record's "workstory_id" value
 * @method integer         getPersonId()     Returns the current record's "person_id" value
 * @method timestamp       getCreatedAt()    Returns the current record's "created_at" value
 * @method timestamp       getUpdatedAt()    Returns the current record's "updated_at" value
 * @method Person          getPerson()       Returns the current record's "Person" value
 * @method WorkstoryPerson setWorkstoryId()  Sets the current record's "workstory_id" value
 * @method WorkstoryPerson setPersonId()     Sets the current record's "person_id" value
 * @method WorkstoryPerson setCreatedAt()    Sets the current record's "created_at" value
 * @method WorkstoryPerson setUpdatedAt()    Sets the current record's "updated_at" value
 * @method WorkstoryPerson setPerson()       Sets the current record's "Person" value
 * 
 * @package    dfmarketplace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseWorkstoryPerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('workstory_person');
        $this->hasColumn('workstory_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('person_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id'));
    }
}