<?php

/**
 * BaseSkill
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $ProjectSkills
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method Doctrine_Collection getProjectSkills() Returns the current record's "ProjectSkills" collection
 * @method Skill               setId()            Sets the current record's "id" value
 * @method Skill               setName()          Sets the current record's "name" value
 * @method Skill               setProjectSkills() Sets the current record's "ProjectSkills" collection
 * 
 * @package    dfmarketplace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseSkill extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('skill');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Project as ProjectSkills', array(
             'refClass' => 'ProjectSkill',
             'local' => 'skill_id',
             'foreign' => 'project_id'));
    }
}