<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "$IP/includes/DefaultSettings.php" );

# ------------- DEV SETTINGS ----------
$wgShowSQLErrors = true;
$wgDebugDumpSql  = true;
$wgDebugLogFile  = 'C:/xampp/htdocs/w/debug_log.txt';
$wgShowExceptionDetails = true;
error_reporting(E_ALL);
ini_set("display_errors", 1);
$wgEnableParserCache = false;
$wgCachePages = false;

$wgRawHtml = true;


# If PHP's memory limit is very low, some operations may fail.
ini_set( 'memory_limit', '30M' );

# ------------------ END DEV SETTINGS -------------

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
}
## Uncomment this to disable output compression
$wgDisableOutputCompression = true;

$wgSitename         = "Dreamfish";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/w";
$wgScriptExtension  = ".php";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "webmaster@dreamfish.com";
$wgPasswordSender = "webmaster@dreamfish.com";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
$wgDBname           = "network_mediawiki";
$wgDBuser           = "root";
$wgDBpassword       = "root";

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = true;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads       = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

$wgLocalInterwiki   = strtolower( $wgSitename );

$wgLanguageCode = "en";

$wgSecretKey = "d2a422acd2a70afe4e021c44e52fdb2e832c58ef20cd2e12b0976c170057c876";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'monobook';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "http://creativecommons.org/licenses/by-nc-sa/3.0/";
$wgRightsText = "Attribution-Noncommercial-Share Alike 3.0 Unported";
$wgRightsIcon = "http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png";
# $wgRightsCode = "[license_code]"; # Not yet used

$wgDiff3 = "/usr/bin/diff3";

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$wgCacheEpoch = max( $wgCacheEpoch, gmdate( 'YmdHis', @filemtime( __FILE__ ) ) );

## Short URL config, see http://www.mediawiki.org/wiki/Manual:Short_URL
$wgArticlePath = "/w/index.php/$1";
$wgUsePathInfo = true;

## Dreamfish configuration

require_once("$IP/extensions/FCKeditor/FCKeditor.php");
require_once("$IP/extensions/uniwiki/CreatePage/CreatePage.php");
require_once("$IP/extensions/SpecialForm/SpecialForm.setup.php");
require_once( "$IP/extensions/recaptcha/ReCaptcha.php" );
$recaptcha_public_key = '6Les_QcAAAAAAGxcW2ZZOlgbsMKL6AuwzCNM-D2a';
$recaptcha_private_key = '6Les_QcAAAAAAKfygvOXAbuAqZ3dznboQHhZ0ZMN';

# require_once( "$IP/extensions/Gadgets/Gadgets.php" );

require_once( "$IP/extensions/StubManager/StubManager.php" );
require_once( "$IP/extensions/ImageLink/ImageLink.php" );


include("extensions/SecureHTML.php");
$shtml_keys = array(
      'primary key' => '210herring',
    );

$wgExtraNamespaces[100] = "Daylog";
$wgExtraNamespaces[101] = "Daylog_talk";
$wgExtraNamespaces[102] = "Meta";
$wgExtraNamespaces[103] = "Meta_talk";

$wgFCKEditorToolbarSet = "Wiki";
$wgDefaultSkin = 'dreamfish';
$wgLocaltimezone = 'PST8PDT';
$wgEmailConfirmToEdit = true;
$wgRCMaxAge = 5184000; # 60 days

$wgShowExceptionDetails = true;
#----Widgets
#http://www.mediawiki.org/wiki/Extension:Widget
#Widgets Extension Mon Aug 31 14:00:41 EDT 2009 Bryan Smith
require_once("$IP/extensions/Widgets/Widgets.php");
#Make Widgets only editable by sysop
$wgGroupPermissions['sysop']['editwidgets'] = true;
##---ManageCategories
#http://www.mediawiki.org/wiki/Extension:ManageCategories
# ManageCategories Extension Mon Aug 31 14:07:48 EDT 2009 Bryan Smith
require_once("$IP/extensions/managecategories/managecategories.php");
##---Mailman
#http://www.mediawiki.org/wiki/Extension:Mailman
#Mailman Extension Mon Aug 31 14:15:45 EDT 2009 Bryan Smith
require_once("extensions/mailman.php");
##---NiceCategoryList2
#http://www.mediawiki.org/wiki/Extension:NiceCategoryList2
#NiceCategoryList2 Extension Mon Aug 31 14:25:09 EDT 2009 Bryan Smith
require_once("$IP/extensions/NiceCategoryList.php");
##---RenameUser
#http://www.mediawiki.org/wiki/Extension:Renameuser
#RenameUser Extension Fri Oct  9 01:30:09 EDT 2009 Bryan Smith
require_once("$IP/extensions/Renameuser/SpecialRenameuser.php");
require_once("$IP/skins/MonoBook.php");
#Give sysops permissions to change users name
$wgGroupPermissions['sysop']['renameuser'] = true;

require_once("$IP/extensions/FlowProcessor/FlowProcessor.php");
