<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/12/27 08:03:42

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=symfony',
  'username' => 'symfony',
  'password' => 'symfony',
  'name' => 'doctrine',
)),);
