Project:
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    title: { type: string(255), notnull: true }
    name: { type: string(255), notnull: true }
    deadline: { type: date, notnull: true }
    description: { type: string(), notnull: true }
    created_at: { type: timestamp(25), notnull: true }
    updated_at: { type: timestamp(25), notnull: true }
  relations:
    Skills:
      class: Skill
      foreignAlias: ProjectSkills
      refClass: ProjectSkill
      local: project_id
      foreign: skill_id

Skill:
  columns:
    id: { type: integer, primary: true }
    name: { type: string(255) }

ProjectSkill:
  columns:
    project_id: { type: integer, primary: true }
    skill_id: { type: integer, primary: true }
  relations:
    Project: { local: project_id, foreign: id, foreignAlias: ProjectSkills }
    Skill: { local: skill_id, foreign: id, foreignAlias: ProjectSkills }


