Project:
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name: { type: string(255), notnull: true }
    user_name: { type: string(255), notnull: true }
    description: { type: string(), notnull: true }
    created_at: { type: timestamp(25), notnull: true }
    updated_at: { type: timestamp(25), notnull: true }
  relations:
    Skills:
      class: Skill
      foreignAlias: ProjectSkills
      refClass: ProjectSkill
      local: project_id
      foreign: skill_id
    Values: 
      class: Value
      foreignAlias: ProjectValues
      refClass: ProjectValue
      local: project_id
      foreign: value_id
    Requests:
      type: many
      class: ProjectRequest
      foreignAlias: ProjectRequests
      local: id
      foreign: project_id

ProjectRequest:
  columns:
    id: { type: integer(8), autoincrement: true, primary:true }
    project_id: { type: integer, notnull: true }
    request: { type: string(255) }
    deadline: { type: date }
  relations:
    Project: { local: project_id, foreign: id }

Skill:
  columns:
    id: { type: integer, primary: true }
    name: { type: string(255) }

Value:
  columns:
    id: { type: integer, primary: true }
    name: { type: string(255) }
    type: { type: string(255) }

ProjectSkill:
  columns:
    project_id: { type: integer, primary: true }
    skill_id: { type: integer, primary: true }
  relations:
    Project: { local: project_id, foreign: id, foreignAlias: ProjectSkills }
    Skill: { local: skill_id, foreign: id, foreignAlias: ProjectSkills }

ProjectValue:
  columns:
    project_id: { type: integer, primary: true }
    value_id: { type: integer, primary: true }
  relations:
    Project: { local: project_id, foreign: id, foreignAlias: ProjectValues }
    Valuel: { local: value_id, foreign: id, foreignAlias: ProjectValues }


